[package]
version = "0.1.0"
name = "aggregation-script"
edition = "2021"

[dependencies]
hex = "0.4.3"
sp1-sdk = { path = "../../../sdk" }
tracing = "0.1.40"

[build-dependencies]
sp1-helper = { path = "../../../helper" }
